name: sales-prediction
channels:
- conda-forge
dependencies:
- python=3.11.11
- pip<=25.1
- pip:
  - mlflow==2.11.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.2.3
  - protobuf==4.25.3
  - jaraco-collections==5.1.0
  - jaraco-context==5.3.0
  - jaraco-functools==4.0.1
  - jaraco-text==3.12.1
  - matplotlib==3.10.1
  - more-itertools==10.3.0
  - pyyaml==6.0.2
  - requests==2.32.3
  - scikit-learn==1.2.2
  - scipy==1.15.2
  - statsmodels==0.14.4
  - xgboost==3.0.0
  - tensorflow-intel==2.17.0
name: mlflow-env
